name: 'Deploy'
on:
  push:
    branches:
      - 'main'
      - "dev-*"

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'

jobs:
  build:
    name: 'build'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-node@v4'
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm ci'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Build application'
        run: 'npm run build'

      - name: 'Build and push'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: min-side

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Deploy'
        uses: 'nais/deploy/actions/deploy@v2'
        env:
          CLUSTER: 'dev-gcp'
          RESOURCE: nais/dev-gcp/nais.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Deploy'
        uses: 'nais/deploy/actions/deploy@v2'
        env:
          CLUSTER: 'prod-gcp'
          RESOURCE: nais/prod-gcp/nais.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}